### ISSUE TITLE
ENETUNREACH issue

### ISSUE THREAD

**Issue by jaquesp** [macnow/homebridge-platform-orvibo#3]
Good morning - just in the last few days I've seen a number of the following errors which cause homebridge to crash almost hourly - could you provide any advice?

`Dec  6 08:56:11 raspberrypi homebridge[1870]: [12/6/2016, 8:56:11 AM] New Orvibo found: Socket [accf23931746]
Dec  6 08:56:12 raspberrypi homebridge[1870]: [12/6/2016, 8:56:12 AM] Subscription to accf23931746 successful!
Dec  6 08:56:13 raspberrypi homebridge[1870]: [12/6/2016, 8:56:13 AM] A device has been queried. Name (if set): TV Radio
Dec  6 08:56:13 raspberrypi homebridge[1870]: [12/6/2016, 8:56:13 AM] Orvibo Online: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ [accf23931746]
Dec  6 08:56:13 raspberrypi homebridge[1870]: [12/6/2016, 8:56:13 AM] Configuring: TV Radio
Dec  6 08:56:36 raspberrypi homebridge[1870]: /usr/local/lib/node_modules/homebridge-platform-orvibo/node_modules/node-orvibo/index.js:723
Dec  6 08:56:36 raspberrypi homebridge[1870]: if (err) throw err; // Error? CRASH AND BURN BB!
Dec  6 08:56:36 raspberrypi homebridge[1870]: ^
Dec  6 08:56:36 raspberrypi homebridge[1870]: Error: send ENETUNREACH 255.255.255.255:10000
Dec  6 08:56:36 raspberrypi homebridge[1870]: at Object.exports._errnoException (util.js:1026:11)
Dec  6 08:56:36 raspberrypi homebridge[1870]: at exports._exceptionWithHostPort (util.js:1049:20)
Dec  6 08:56:36 raspberrypi homebridge[1870]: at SendWrap.afterSend [as oncomplete] (dgram.js:407:11)
Dec  6 08:56:36 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dec  6 08:56:36 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Dec  6 08:56:46 raspberrypi systemd[1]: homebridge.service holdoff time over, scheduling restart.`

Thanks in advance,
Paul

**Comment by jaquesp** [comment]
Can anyone advise? This is happening every few hours or so now.

**Comment by jaquesp** [comment]
can anyone help? I've had to disable the platform and stop using the orvibo due to the number of occasions it was crashing homebridge.

**Comment by arvidbjorkstrom** [comment]
It seems your raspberry pi is unable to reach the broadcast address of 255.255.255.255.
The call is initated by the [node_orvibo](https://github.com/Grayda/node-orvibo) package this one depends on.
The 255.255.255.255 address should always be reachable as long as you have a working network connection. Your error sounds like your network connection is intermittent for some reason, and you're loosing connection. If you're using a wifi dongle, maybe check the connection strength?

**Comment by jaquesp** [comment]
Thanks for this. This happens when the wifi drops for some reason - normally it's 100% effective, but i restart the router for some reason the wifi becomes unavailable and the orvibo platform crashes homebridge. Is there way of handling this? Some other plugins report the unreachable status, and wait for a reconnect....
